### PR TITLE
Add Docker config

### PR DESCRIPTION
**Pull request by zednis**
Added Docker config file and tomcat-related scripts for docker deployments.

### CODE REVIEW

**Comment by zednis** [comment]
CODE REVIEW!

Here is the pull request process.  You can see the commit(s) that I am proposing to merge from my branch into the master branch.  You can leave general comments or make comments in-line in the code.

The pull request process knows there is a Travis-CI build for this commit (see above, failed because of the missing RDF test file issue with S2S).

**Comment by zednis** [comment]
PS - the reason the docker config stuff was originally committed to the php-caching feature branch is because I forgot which branch I was working on :confused:

**Comment by mrpatrickwest** [comment]
:-1: Let's get the travis ci build to pass.

**Comment by zednis** [comment]
...OK  :cry:

**Comment by zednis** [comment]
Travis-CI build is now successful :smile:

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
